const express = require('express')
const router = express.Router();
const connection = require('../config/db');


//ADD PRODUCT TO CART
//LIST PRODUCT TO CART
//LIST PRODUCT BY ID
//ADD PRODUCT TO WISHLIST
//LIST TO WISHLIST
//INCREMENT IN CART
//DECREMENT IN CART
//DELETE FROM CART
//CLEAN CART
//UPDATE QUANTITY
//GET TOTAL CART
//GET PRICE TO CART
//CHECKOUT
//ORDER BY ID
//ORDER PENDING
//ORDER COMPLETE
//ORDER DETAIL
//ORDER PROCESSING
//ORDER DELIVERED
//ORDER CANCELLED
//PAYMENT
//ALL PRODUCT
//POPULAR PRODUCT
//GET PRODUCT BY ID
//SEARCH PRODUCT
//GET BY CATEGORY ID
//GET NEW RIVAL
//GET HOT PRODUCTS
//STOCK OUT
//GET NEW ARRIVAL
//GET HOT PRODUCTS
//GET BY PRICE
//GET BY CATEGORY NAME
//LIST PRODUCT BY SHOP
//CATEGORY PRODUCT BY SHOP
//FIND SHOP BY DISTANCE FROM USER
//SHOW ALL SLIDER
//SET RATING IN PRODUCT
//SET RATING IN SHOPPING
//SEND MESSAGE



