//CREATE PRODUCT
//GET ALL PRODUCT
//GET PRODUCT BY ID
//UPDATE PRODUCT
//DELETE PRODUCT
//GET PRODUCT BY NAME
//SEARCH PRODUCT
//GET PRODUCT BY CATEGORY ID
//GET PRODUCT BY CATEGORY NAME
//GET PRODUCT BY SHOP ID
//GET PRODUCT BY SHOP NAME
//GET PRODUCT BY SHOP NAME
//REACTIVATE/DEACTIVATE PRODUCT
//SEND MESSAGE
